/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.cliente.CadCliente;
import app.cliente.ExcluirCliente;
import app.cliente.VCliente;
import app.consultas.ConsultaDois;
import app.consultas.ConsultaQuatro;
import app.consultas.ConsultaTres;
import app.consultas.ConsultaUm;
import app.func.CadFunc;
import app.func.ExcluirFunc;
import app.func.VFunc;

/**
 *
 * @author Elias
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        vcl = new javax.swing.JButton();
        cadcl = new javax.swing.JButton();
        atcl = new javax.swing.JButton();
        vcl1 = new javax.swing.JButton();
        cadcl1 = new javax.swing.JButton();
        atcl1 = new javax.swing.JButton();
        atcl2 = new javax.swing.JButton();
        atcl3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        atcl4 = new javax.swing.JButton();
        atcl5 = new javax.swing.JButton();
        atcl6 = new javax.swing.JButton();
        atcl7 = new javax.swing.JButton();
        atcl8 = new javax.swing.JButton();
        atcl9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setText("Sair");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        vcl.setText("Visualizar Clientes");
        vcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vclActionPerformed(evt);
            }
        });

        cadcl.setText("Cadastrar Cliente");
        cadcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadclActionPerformed(evt);
            }
        });

        atcl.setText("Alterar Cliente");
        atcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atclActionPerformed(evt);
            }
        });

        vcl1.setText("Visualizar Funcionarios");
        vcl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcl1ActionPerformed(evt);
            }
        });

        cadcl1.setText("Cadastrar Funcionarios");
        cadcl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadcl1ActionPerformed(evt);
            }
        });

        atcl1.setText("Alterar Funcionario");
        atcl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl1ActionPerformed(evt);
            }
        });

        atcl2.setText("Excluir Cliente");
        atcl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl2ActionPerformed(evt);
            }
        });

        atcl3.setText("Excluir Funcionario");
        atcl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Armazem !N$4N0");

        atcl4.setText("Consulta 3");
        atcl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl4ActionPerformed(evt);
            }
        });

        atcl5.setText("Buscar carga por data");
        atcl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl5ActionPerformed(evt);
            }
        });

        atcl6.setText("Consulta 2");
        atcl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl6ActionPerformed(evt);
            }
        });

        atcl7.setText("Consulta 1");
        atcl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl7ActionPerformed(evt);
            }
        });

        atcl8.setText("Consulta 4");
        atcl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl8ActionPerformed(evt);
            }
        });

        atcl9.setText("Consulta 5");
        atcl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcl9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 343, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cadcl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atcl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vcl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atcl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atcl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atcl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atcl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atcl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atcl9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(atcl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadcl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vcl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atcl3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(atcl5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vcl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadcl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atcl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atcl2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vcl1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadcl1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atcl1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atcl3)))
                .addGap(27, 27, 27)
                .addComponent(atcl7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atcl6)
                .addGap(5, 5, 5)
                .addComponent(atcl4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atcl8)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atcl5)
                    .addComponent(atcl9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit( 0 );
    }//GEN-LAST:event_jButton6ActionPerformed

    private void vclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vclActionPerformed
        new VCliente().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_vclActionPerformed

    private void cadclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadclActionPerformed
        new CadCliente(true).setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_cadclActionPerformed

    private void atclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atclActionPerformed
        new CadCliente(false).setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atclActionPerformed

    private void vcl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcl1ActionPerformed
        new VFunc().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_vcl1ActionPerformed

    private void cadcl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadcl1ActionPerformed
        new CadFunc(true).setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_cadcl1ActionPerformed

    private void atcl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl1ActionPerformed
        new CadFunc(false).setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl1ActionPerformed

    private void atcl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl2ActionPerformed
        new ExcluirCliente().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl2ActionPerformed

    private void atcl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl3ActionPerformed
       new ExcluirFunc().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl3ActionPerformed

    private void atcl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl4ActionPerformed
        new ConsultaTres().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl4ActionPerformed

    private void atcl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl5ActionPerformed
        new ConsultaCarga().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl5ActionPerformed

    private void atcl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl6ActionPerformed
        new ConsultaDois().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl6ActionPerformed

    private void atcl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl7ActionPerformed
        new ConsultaUm().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl7ActionPerformed

    private void atcl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl8ActionPerformed
        new ConsultaQuatro().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl8ActionPerformed

    private void atcl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcl9ActionPerformed
        new ConsultaQuatro().setVisible( true );
        this.setVisible( false );
    }//GEN-LAST:event_atcl9ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atcl;
    private javax.swing.JButton atcl1;
    private javax.swing.JButton atcl2;
    private javax.swing.JButton atcl3;
    private javax.swing.JButton atcl4;
    private javax.swing.JButton atcl5;
    private javax.swing.JButton atcl6;
    private javax.swing.JButton atcl7;
    private javax.swing.JButton atcl8;
    private javax.swing.JButton atcl9;
    private javax.swing.JButton cadcl;
    private javax.swing.JButton cadcl1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton vcl;
    private javax.swing.JButton vcl1;
    // End of variables declaration//GEN-END:variables
}
